//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Repository.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedTypeMaster
    {
        public int ID { get; set; }
        public string UniqueID { get; set; }
        public string BedTypeCode { get; set; }
        public string BedTypeName { get; set; }
        public string CompanyUniqueID { get; set; }
        public string ActiveStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDate { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
    }
}
